import def_kWh
# calculates the cost of electricity generated by the device per year

def go():
    try:
        def_kWh.count_kwh()
        def_kWh.save_kwh()
    except:
        print('The report has not been saved.')


go()
